DP-1168 install ros package + proj mobtest
MOV-AI/.github pull request #160
Opened 2023-06-19 10:30 UTC by duartecoelhomovai

2023-06-19 10:35 UTC, AlexFernandes-MOVAI requested changes
Please add a link to a working execution of this workflow

2023-06-19 10:36 UTC, AlexFernandes-MOVAI commented
and resolve conflicts

2023-06-19 10:55 UTC, diasdm requested changes
Please update the PR description with impacts. It is required for a `build-requirements.txt` to exist in the repo?

2023-06-20 11:28 UTC, duartecoelhomovai commented
https://github.com/MOV-AI/movai_autonomy_pack/actions/runs/5321449666/jobs/9637666868

2023-06-20 12:39 UTC, AlexFernandes-MOVAI approved these changes

2023-06-21 12:47 UTC, diasdm commented on .github/workflows/ros-workflow.yml
> +      - name: Mobtest
```suggestion
      - name: Mobtest project validations
```

2023-06-21 12:47 UTC, diasdm approved these changes

2023-06-21 14:17 UTC, merged