add install logs
MOV-AI/.github pull request #161
Opened 2023-06-19 14:45 UTC by duartecoelhomovai

2023-06-19 14:58 UTC, diasdm requested changes
Won't this generate multiple artifacts with the same name? Consider using the existing artifact to store installation logs too

2023-06-19 15:01 UTC, AlexFernandes-MOVAI requested changes

2023-06-19 15:01 UTC, AlexFernandes-MOVAI commented on .github/workflows/integration-build-platform.yml
> +          journalctl -u movai-service -t mobros -n 100 > install_logs/spawner-firmware.log
use something like `journalctl -u movai-service --since '1hour ago' &> "movai-service.log"`

2023-06-19 15:11 UTC, diasdm commented
This was looking familiar... We added movai-service logs but only on v1: https://github.com/MOV-AI/.github/pull/143

2023-06-19 15:52 UTC, diasdm commented
I've open a PR cherry-picking what we have done before, this way all tests save the same logs in the same manner, see #162

2023-06-20 08:04 UTC, duartecoelhomovai commented
> I've open a PR cherry-picking what we have done before, this way all tests save the same logs in the same manner, see #162

Adapted to it

2023-06-20 12:41 UTC, AlexFernandes-MOVAI approved these changes

2023-06-21 12:42 UTC, diasdm requested changes

2023-06-21 12:42 UTC, diasdm commented on .github/workflows/integration-build-platform.yml
> +      - name: Collect Install logs
I think these changes can be deleted, we have the logs 2 steps down

2023-06-22 14:51 UTC, diasdm requested changes

2023-06-22 14:51 UTC, diasdm commented on .github/workflows/integration-build-product.yml
> +          name: install_logs
It should be different no? Not sure what happens if they are the same
```suggestion
          name: install_simulator_logs
```

2023-06-23 07:29 UTC, diasdm approved these changes

2023-06-23 07:46 UTC, merged