Add pnpm as an option other than npm
MOV-AI/.github pull request #239
Opened 2024-02-01 16:12 UTC by quirinpa

2024-02-05 14:30 UTC, AlexFernandes-MOVAI reviewed
please provide a description and working pipeline execution

2024-02-05 16:31 UTC, duartecoelhomovai requested changes

2024-02-05 16:31 UTC, duartecoelhomovai commented on .github/workflows/frontend-workflow.yml
> +        npm install -g pnpm
I would suggest creating a new version of the agent where this runs and have this installs there.

2024-02-05 16:31 UTC, duartecoelhomovai commented on .github/workflows/frontend-workflow.yml
> +        npm install -g pnpm
I can help on that

2024-02-05 16:31 UTC, duartecoelhomovai commented on .github/workflows/frontend-workflow.yml
> +        npm install -g pnpm
Lets not merge this into v2. 
I will create a new branch v2.1, and that will be the target branch

2024-02-05 17:12 UTC, duartecoelhomovai commented on .github/workflows/frontend-workflow.yml
> +        npm install -g pnpm
qa/npm-buildserver:v1.0.0 has it

2024-02-16 15:45 UTC, quirinpa commented on .github/workflows/frontend-workflow.yml
> +        npm install -g pnpm
Is this correct?
      image: registry.aws.cloud.mov.ai/qa/npm-buildserver:v1.0.0

2024-02-16 16:37 UTC, duartecoelhomovai approved these changes

2024-02-16 16:37 UTC, merged