Feat/packer v2 gh runner img
MOV-AI/.github pull request #254
Opened 2024-04-05 13:15 UTC by DenisBorzenkov

gh-runner pipeline

2024-04-05 14:35 UTC, AlexFernandes-MOVAI commented on .github/workflows/packer-gh-runner-img.yml
> +    runs-on: packer-runner
this needs to be a self-hosted runner

2024-04-05 14:39 UTC, AlexFernandes-MOVAI reviewed
Please review the steps for :
- build on push: local build only
- staging on merge to main: build and store on some place that can be reused STAGING_DIR
- deployment on release of official version:  read the artifacts from STAGING_DIR to copy them to NAS

2024-04-11 13:00 UTC, AlexFernandes-MOVAI requested changes
just a change  on the proxmox URL

2024-04-11 13:00 UTC, AlexFernandes-MOVAI commented on .github/workflows/packer-workflow-img.yml
> +  PROXMOX_NFS_SERVER_URL: "https://hel.mov.ai:8006/#v1:0:=storage%2Fbb-8%2Fnas-mary:4:5:=contentIso"
```suggestion
  PROXMOX_NFS_SERVER_URL: "https://hel.mov.ai:8006/#v1:0:=storage%2Fhel%2Fnas-mary:4:5:=contentIso:::::"
```

2024-04-12 09:51 UTC, DenisBorzenkov commented on .github/workflows/packer-gh-runner-img.yml
> +    runs-on: packer-runner
done

2024-04-12 09:52 UTC, merged