DP 1491 - parameterize cluster
MOV-AI/.github pull request #257
Opened 2024-04-10 16:02 UTC by mariana-dias-alves

- [ ] Make sure you are opening from a **topic/feature/bugfix branch**
- [ ] Ensure that the PR title represents the desired changes
- [ ] Ensure that the PR description detail the desired changes
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

[^note]:
    Put an `x` into the [ ] to show you have filled the information.
    The template comes from https://github.com/MOV-AI/.github/blob/master/.github/pull_request_template.md
    You can override it by creating .github/pull_request_template.md  in your own repository

2024-04-11 08:14 UTC, duartecoelhomovai requested changes

2024-04-11 08:14 UTC, duartecoelhomovai commented on .github/workflows/integration-build-product.yml
>            TF_VAR_bios: "ovmf"
On line 1254, we could try to compare the differences of the image u22dci-gpu2 which is the one used by sanity tests and we know its on the 3 cluster nodes.
For this approach the image must exist on all.

2024-04-11 08:14 UTC, duartecoelhomovai commented
PS: mariana is a machine!

2024-04-16 14:25 UTC, AlexFernandes-MOVAI approved these changes

2024-04-16 14:26 UTC, merged