Add task to retrive nb of delivered objects
MOV-AI/.github pull request #264
Opened 2024-04-17 17:52 UTC by mariana-dias-alves

DO NOT MERGE

- Save simulation test outputs in artifact `sim-outputs` to be extracted to influxdb cloud.

Test (cancelled on purpose, but tasks added passed): https://github.com/MOV-AI/project-movai-studio/actions/runs/8750655304/job/24023733460

---------------

- [x] Make sure you are opening from a **topic/feature/bugfix branch**
- [x] Ensure that the PR title represents the desired changes
- [x] Ensure that the PR description detail the desired changes
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

[^note]:
    Put an `x` into the [ ] to show you have filled the information.
    The template comes from https://github.com/MOV-AI/.github/blob/master/.github/pull_request_template.md
    You can override it by creating .github/pull_request_template.md  in your own repository

2024-04-18 08:44 UTC, AlexFernandes-MOVAI requested changes

2024-04-18 08:44 UTC, AlexFernandes-MOVAI commented on .github/workflows/integration-build-product.yml
> +        uses: andstor/file-reader-action@v1
this github action is unmaintained, please use another way

2024-04-18 08:44 UTC, AlexFernandes-MOVAI commented on .github/workflows/integration-build-product.yml
> +        uses: andstor/file-reader-action@v1
maybe: https://github.com/marketplace/actions/github-file-reader-action-v2

2024-04-24 13:13 UTC, duartecoelhomovai approved these changes

2024-04-24 13:26 UTC, AlexFernandes-MOVAI approved these changes

2024-04-24 13:29 UTC, merged