Verify no mov-ai duplicates
MOV-AI/.github pull request #287
Opened 2024-06-18 11:20 UTC by quirinpa

- [FP-2834](https://movai.atlassian.net/browse/FP-2834): Remove duplicated dependencies on all apps by moving peer dependencies (only part of the work for this task)

2024-06-18 15:35 UTC, AlexFernandes-MOVAI reviewed
proposition, just reviewing the code for better readility

2024-06-18 15:35 UTC, AlexFernandes-MOVAI commented on .github/workflows/frontend-workflow.yml
> +	if: ${{ inputs.custom_deps_not_dup == 'true' }}
NPM can be defined as an env var, with
```suggestion
	if: ${{ inputs.custom_deps_not_dup == 'true' }}
	env:
	   NPM: ${{ inputs.pm }}
```

2024-06-18 15:35 UTC, AlexFernandes-MOVAI commented on .github/workflows/frontend-workflow.yml
> +	    if test "$NPM" = "npm"; then
alias `may_tail` is a working solution but I would prefer to have 2 sets of functions for better readibility:
`dupe_check_npm()`
`dupe_check_other()`

each one being called in a dedicated task of the workflow maybe:
`- name: Validate specified deps not duplicated with NPM`
`- name: Validate specified deps not duplicated with other`

2024-06-18 16:06 UTC, duartecoelhomovai commented
I'm not really up to date with what was discussed in frontend channel. @diasdm

2024-06-19 09:59 UTC, duartecoelhomovai commented
Test the pipeline using this branch and please paste it here the run.

2024-07-04 10:44 UTC, diasdm requested changes
Before merging this we need to fully understand how we'll manage dependencies on EE 2.4.1 apps, which we don't know ATM

2025-03-03 15:21 UTC, AlexFernandes-MOVAI commented
Unmaintained PR

2025-03-03 15:21 UTC, closed without merging