Feature/add cpp
MOV-AI/.github pull request #6
Opened 2022-01-13 16:56 UTC by duartecoelhomovai

Template for CPP, developed and tested against :

https://github.com/MOV-AI/movai_ign_plugins/pull/5

- [x] Make sure you are opening from a **topic/feature/bugfix branch**
- [x] Ensure that the PR title represents the desired changes
- [x] Ensure that the PR description detail the desired changes
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

[^note]:
    Put an `x` into the [ ] to show you have filled the information.
    The template comes from https://github.com/MOV-AI/.github/blob/master/.github/pull_request_template.md
    You can override it by creating .github/pull_request_template.md  in your own repository

2022-01-14 10:19 UTC, AlexFernandes-MOVAI requested changes
Nice and sweet, not tested but carefully read.
Some questions:
- for now we build for noetic/focal only, this can be done in  second roll
- no arguments are passed to cmake, but we should have at least the release type
- unittest can also be launched if existing

2022-01-14 10:19 UTC, AlexFernandes-MOVAI commented on .github/workflows/cpp-workflow.yml
> +        cmake .. -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/
here we should have some arguments / env vars to customise the build, for example in https://github.com/marketplace/actions/build-cmake they present:

'''
          build-dir: ${{ runner.workspace }}/build
          # will set the CC & CXX for cmake
          cc: gcc
          cxx: g++
          build-type: Release
          # Extra options pass to cmake while configuring project
          configure-options: -DCMAKE_C_FLAGS=-w32 -DPNG_INCLUDE=OFF
          run-test: true
          ctest-options: -R mytest
          # install the build using cmake --install
          install-build: true
          # run build using '-j [parallel]' to use multiple threads to build
          parallel: 14
'''
or here https://github.com/marketplace/actions/build-c-project

2022-01-14 10:21 UTC, duartecoelhomovai commented
> Nice and sweet, not tested but carefully read. Some questions:
> 
> * for now we build for noetic/focal only, this can be done in  second roll
> * no arguments are passed to cmake, but we should have at least the release type
> * unittest can also be launched if existing

Totally agree. Unfortunally was done in best effort. But looks like some nice increments yes.

2022-10-12 09:12 UTC, AlexFernandes-MOVAI approved these changes

2022-10-12 09:13 UTC, merged