Feature/qap 1700 continue on error ee platform suites
MOV-AI/.github pull request #86
Opened 2023-01-18 17:12 UTC by diasdm

Changes:
* Set continue of failure for all QA suites github action step
* Add step to fail pipeline if any QA suite failed which had not continue on failure parameter set to true
* Add parameters for flow tests

These changes improve QA experience by:
* running all suites before failing pipeline
* allow QA members to temporarily set stages to continue on failure without having to change the pipeline

These changes are not backwards compatible. Do we accept the compatibility break?

2023-01-18 17:18 UTC, almeidamov requested changes

2023-01-18 17:18 UTC, almeidamov commented on .github/workflows/integration-build-platform.yml
> +      - name: Fail execution if tests failed
QA tests*

2023-01-18 17:38 UTC, duartecoelhomovai requested changes
We can do parallel stages if they do not have dependencies between them.
I can help you architecture'ize it.
Request changes is for myself.

2023-01-19 12:02 UTC, almeidamov approved these changes

2023-02-14 11:30 UTC, AlexFernandes-MOVAI commented
@diasdm and @duartecoelhomovai please review conflicts

2023-02-23 14:50 UTC, closed without merging

2023-02-23 14:51 UTC, diasdm commented
Due to the tests now running in parallel, there is less motivation to have this